# Copyright (C) 2020 - present Juergen Zimmermann, Florian Rusch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

---
# extends:
  # https://stylelint.io
  # - stylelint-config-standard
  # - stylelint-config-sass-guidelines
  #- stylelint-config-twbs-bootstrap/scss

# https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules/list.md
rules:
  alpha-value-notation: number
  at-rule-no-unknown: true
  block-closing-brace-newline-after: always
  block-no-empty: true
  block-opening-brace-newline-after: always
  color-named: always-where-possible
  color-no-invalid-hex: true
  comment-empty-line-before: always
  comment-no-empty: true
  declaration-bang-space-after: never
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-single-line-max-declarations: 1
  declaration-empty-line-before: never
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  font-weight-notation: named-where-possible
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-url-no-scheme-relative: true
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  media-feature-name-no-unknown: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  # no-empty-source: false
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  number-max-precision: 2
  property-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  unit-case: lower
  unit-no-unknown: true
  value-keyword-case: lower
  # value-list-comma-newline-after: false
  # declaration-colon-newline-after: false
  # declaration-block-no-redundant-longhand-properties: false
